### ISSUE TITLE
Issue running the plugin

### ISSUE THREAD

**Issue by irinel-dan** [bertholdm/TextDiff#2] opened 2023-02-02 21:02 UTC
Hello,
Thank you for your effort in creating this plugin, nice job.
I do have some issues.
I'm using a MacBook Pro with Monterey 12.6 and I have this issue:

On my env I cannot use the plugin because I have the following error, found using the debug mode:

```
sh: -c: line 0: syntax error near unexpected token \`('
sh: -c: line 0: \`ebook-convert "/Users/i.dan/Calibre Library Test/Sven Hassel/Legiunea blestematilor (38)/Legiunea blestematilor - Sven Hassel.epub" "/Users/i.dan/Calibre Library Test/Sven Hassel/Legiunea blestematilor (38)/Legiunea blestematilor - Sven Hassel_epub_38.txt" -v -v  --sr1-search (?m)^\s*$ --sr1-replace ""'
```

I've done some testing on my machine and ran the command in terminal and it works if I add double-quotes for the --sr1-search value, like this:
` --sr1-search "(?m)^\s*$"`
I do not understand how it works on other envs...

I tried changing the code myself, and loaded the plugin manually, but now I have another error:
`ebook-convert command not found`

Can you tell me what I'm doing wrong when I try to load the plugin manually?
Thank you,
Irinel

**Comment by bertholdm** [comment] 2023-02-03 14:59
Hello Irinel,
Thanks for the detailed report. The issue is (I hope so, I've no Mac at hand to test it) fixed in version 1.1.2, now published at 
https://www.mobileread.com/forums/showthread.php?p=4275043#post4275043.
Thank you,
bertholdm

**Closed as completed** 2023-02-03 15:00 UTC
